info:
  app:
    name: @project.name@
    artifact: @project.artifactId@
    description: @project.description@
    version: @project.version@

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/dimval?useSSL=false
    username: dbuser
    password: dbpassword
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 10
      maximum-pool-size: 20
      pool-name: dim-val-api-pool
      auto-commit: true
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 100
  main:
    banner-mode: "off"
  data:
    web:
      pageable:
        default-page-size: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

services:
  cors:
    enabled: true
    path-pattern: "/**"
    allow-credentials: false
    allow-headers: "*"
    allow-origins: "*"
    allow-methods: ["GET","HEAD","POST"]
    max-age-sec: 1800
  base-url: /dim-val/api
  admin-base-url: /dim-val-admin/api
  attr-tree-links:
    - parent: device.geo.ext.netacuity.country
      leaf: device.geo.ext.netacuity.region
    - parent: device.geo.ext.netacuity.country
      leaf: device.geo.ext.netacuity.metro

server-auth:
  enabled: true
  realm: dim-val-api-svc
  principals:
    - username: user2
      password: password2
      roles: all

server-api-roles:
  upload: upload, all
  download: download, all
  query: query, all

management:
  endpoints:
    web:
      base-path: /status
      exposure:
        include: health
  endpoint:
    health:
      defaults:
        enabled: false